### ISSUE TITLE
npm run buildcss Error

### ISSUE THREAD

**Issue by yyqyangyongqiang** [andreynering/sudoku#5]
PS D:\Project\sudoku-1> npm install -g less-plugin-clean-css
+ less-plugin-clean-css@1.5.1
PS D:\Project\sudoku-1> npm run buildcss

> sudoku@0.0.0 buildcss D:\Project\sudoku-1
> lessc --clean-css ./css/main.less bundle.css

Unable to load plugin clean-css please make sure that it is installed under or at the same level as less
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sudoku@0.0.0 buildcss: `lessc --clean-css ./css/main.less bundle.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sudoku@0.0.0 buildcss script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Software\Work\node\node_cache\_logs\2020-10-26T11_45_38_606Z-debug.log

Can you help me ？

**Comment by andreynering** [comment]
Hi @yyqyangyongqiang,

Sorry, but this is not something I maintain. I'll even archive this repository.
